-----BEGIN PRIVATE KEY-----
MIdsvGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXPc5za0aPuBHlbtq
SnEMxnYULBKraT0sL5OVzVvaWw5WvgCgYIKoZIzj0jkDAQehRANCAATgukFClF49fJI8
dbCDq9dsvsdvsvd4I8NrLLRWg0R6rJZ5EzeiNrtNow3QLCEI/byMdYVHdS7khbh+MSOPX/Hn7
apF+23ap
-----END PRIVATE KEY-----
